name = "p10t"
version = "0.1.0"
defaultTargets = ["p10t"]

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
scope = "leanprover-community"

[[lean_lib]]
name = "P10t"

[[lean_exe]]
name = "p10t"
root = "P10t.Main"
supportInterpreter = true
